version: "3.8"

services:
  compute:
  build:
    context: .
    image: alchemine/base-cde:ubuntu22.04
  volumes:
    - .:/opt/project
  hostname: "dev"
  restart: always
  tty: true
  ipc: host
  privileged: true
